---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
- name: gopath
  temp: {}
steps:
- name: download go modules
  image: golang:1.17.6
  commands:
  - go mod download
  volumes: &volumes
  - name: gopath
    path: /go
- name: golangci-lint
  image: golangci/golangci-lint:v1.50.1-alpine
  commands:
  - golangci-lint run
  volumes: *volumes
- name: test
  image: golang:1.17.6
  commands:
  # bash and cgo seem to be required
  - bash ci/test.sh
  environment:
    CC_TEST_REPORTER_ID:
      from_secret: cc_test_reporter_id
  volumes: *volumes
